name: Django

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Compose        
      uses: ndeloof/install-compose-action@v0.0.1
      with:
        version: v2.1.0
        legacy: false
    - run: docker compose -f docker-compose.tests.yml up --exit-code-from test-django
  linter:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: pip install flake8 djlint
    - name: Run linter
      run: |
        flake8 .
        djlint templates
